# Generated by Django 4.2 on 2023-05-03 10:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comapnyName', models.CharField(max_length=60, null=True)),
                ('advImage', models.FileField(upload_to='addImage')),
            ],
        ),
        migrations.CreateModel(
            name='Attendee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contactNumber', models.CharField(max_length=20, null=True)),
                ('balance', models.PositiveIntegerField(null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventName', models.CharField(max_length=100)),
                ('shortDisc', models.TextField(max_length=200)),
                ('longDisc', models.TextField(max_length=500)),
                ('eventVenue', models.CharField(max_length=150)),
                ('eventDate', models.DateTimeField(auto_now_add=True)),
                ('eventImage', models.ImageField(upload_to='eImage')),
                ('basePrice', models.PositiveIntegerField(null=True)),
                ('eventOrganizer', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='seatCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryName', models.CharField(max_length=20)),
                ('price', models.IntegerField()),
                ('seatAvailable', models.IntegerField()),
                ('active', models.BooleanField()),
                ('event', models.ManyToManyField(to='mainapp.event')),
            ],
        ),
        migrations.CreateModel(
            name='Ticektbooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookingID', models.CharField(max_length=20)),
                ('seatquantity', models.IntegerField()),
                ('totalprice', models.IntegerField()),
                ('bookingDate', models.DateTimeField(auto_now_add=True)),
                ('attende', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.attendee')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.event')),
                ('seat', models.ManyToManyField(to='mainapp.seatcategory')),
            ],
            options={
                'ordering': ['totalprice'],
            },
        ),
    ]
