# Generated by Django 4.2 on 2023-05-02 05:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advImage', models.FileField(upload_to='addImage')),
            ],
        ),
        migrations.CreateModel(
            name='Attendee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contactNumber', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventName', models.CharField(max_length=100)),
                ('shortDisc', models.TextField(max_length=200)),
                ('longDisc', models.TextField(max_length=500)),
                ('eventVenue', models.CharField(max_length=150)),
                ('eventDate', models.DateTimeField(auto_now_add=True)),
                ('eventImage', models.ImageField(upload_to='eImage')),
                ('basePrice', models.PositiveIntegerField(null=True)),
                ('eventOrganizer', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seatType', models.CharField(choices=[('VVIP', 'FIRST CLASS'), ('VIP', 'SECOND CLASS'), ('NORMAL', 'THIRD CLASS')], max_length=20)),
                ('avaiblity', models.IntegerField(null=True)),
                ('price', models.IntegerField(null=True)),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mainapp.event')),
            ],
        ),
        migrations.CreateModel(
            name='Ticektbooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookingID', models.CharField(max_length=20)),
                ('seatquantity', models.IntegerField()),
                ('price', models.IntegerField()),
                ('bookingDate', models.DateTimeField(auto_now_add=True)),
                ('attende', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.attendee')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.event')),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.seat')),
            ],
        ),
        migrations.AddField(
            model_name='attendee',
            name='eventAttending',
            field=models.ManyToManyField(related_name='attendees', to='mainapp.event'),
        ),
        migrations.AddField(
            model_name='attendee',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
