# Generated by Django 4.2 on 2023-05-02 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendee',
            name='eventAttending',
        ),
    ]
