# Generated by Django 4.2 on 2023-05-01 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seatType', models.CharField(choices=[('VVIP', 'FIRST CLASS'), ('VIP', 'SECOND CLASS'), ('NORMAL', 'THIRD CLASS')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Seatsavailable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avaiblity', models.IntegerField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.event')),
                ('seatCategory', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mainapp.seat')),
            ],
        ),
        migrations.CreateModel(
            name='Ticektbooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookingID', models.CharField(max_length=20)),
                ('seatquantity', models.IntegerField()),
                ('price', models.IntegerField()),
                ('bookingDate', models.DateTimeField(auto_now_add=True)),
                ('attende', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.attendee')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.event')),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.seat')),
                ('seatavailable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.seatsavailable')),
            ],
        ),
        migrations.RemoveField(
            model_name='ticketinfo',
            name='attende',
        ),
        migrations.RemoveField(
            model_name='ticketinfo',
            name='ticket',
        ),
        migrations.DeleteModel(
            name='Ticket',
        ),
        migrations.DeleteModel(
            name='Ticketinfo',
        ),
    ]
