# Generated by Django 4.2 on 2023-05-02 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_remove_attendee_eventattending'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticektbooking',
            old_name='price',
            new_name='totalPrice',
        ),
    ]
