# Generated by Django 4.2 on 2023-05-02 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_rename_price_ticektbooking_totalprice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticektbooking',
            old_name='totalPrice',
            new_name='totalprice',
        ),
    ]
