# Generated by Django 4.2 on 2023-05-02 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_rename_totalprice_ticektbooking_totalprice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seat',
            name='event',
        ),
        migrations.AddField(
            model_name='seat',
            name='event',
            field=models.ManyToManyField(null=True, to='mainapp.event'),
        ),
    ]
