# Generated by Django 4.2 on 2023-05-02 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_remove_seat_event_seat_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='seatCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryName', models.CharField(max_length=20)),
                ('seatNumber', models.CharField(max_length=10)),
                ('price', models.IntegerField()),
                ('seatAvailable', models.IntegerField()),
                ('active', models.BooleanField()),
                ('event', models.ManyToManyField(to='mainapp.event')),
            ],
        ),
        migrations.RemoveField(
            model_name='ticektbooking',
            name='seat',
        ),
        migrations.DeleteModel(
            name='Seat',
        ),
        migrations.AddField(
            model_name='ticektbooking',
            name='seat',
            field=models.ManyToManyField(to='mainapp.seatcategory'),
        ),
    ]
