# Generated by Django 4.2 on 2023-05-02 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_seatcategory_remove_ticektbooking_seat_delete_seat_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seatcategory',
            name='seatNumber',
        ),
        migrations.AddField(
            model_name='ticektbooking',
            name='seatNumber',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
