# Generated by Django 4.2 on 2023-05-02 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_remove_seatcategory_seatnumber_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticektbooking',
            options={'ordering': ['totalprice']},
        ),
        migrations.AddField(
            model_name='advertisment',
            name='comapnyName',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
