# Generated by Django 4.2 on 2023-05-03 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_attendee_balance_ticketbooking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticektbooking',
            name='seatNumber',
        ),
    ]
