# Generated by Django 4.2 on 2023-05-03 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_remove_ticektbooking_seatnumber'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TicketBooking',
        ),
    ]
