# Generated by Django 4.2 on 2023-05-03 06:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_delete_ticketbooking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticektbooking',
            name='attende',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.attendee'),
        ),
    ]
